const courses = [
  {
    id: 1,
    title: "Art & Painting",
    description: "Explore your creativity with colors and brushes.",
    location: "Room 101",
    price: 20.0,
    spaces: 5,
    rating: 5,
    image: "https://images.pexels.com/photos/102127/pexels-photo-102127.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 2,
    title: "Music & Guitar Lessons",
    description: "Strum your way to greatness with beginner guitar sessions.",
    location: "Music Room",
    price: 18.0,
    spaces: 5,
    rating: 5,
    image: "https://images.pexels.com/photos/144428/pexels-photo-144428.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 3,
    title: "Drama & Theatre",
    description: "Act, perform, and express yourself with confidence.",
    location: "Auditorium",
    price: 22.0,
    spaces: 5,
    rating: 5,
    image: "https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 4,
    title: "Coding for Kids",
    description: "Learn to build simple apps and games with code!",
    location: "Computer Lab",
    price: 28.0,
    spaces: 5,
    rating: 5,
    image: "https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 5,
    title: "Robotics Club",
    description: "Build and program simple robots in a fun environment.",
    location: "Tech Lab",
    price: 25.0,
    spaces: 5,
    rating: 4,
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 6,
    title: "Chess Club",
    description: "Sharpen your mind with strategy and problem-solving.",
    location: "Library",
    price: 10.0,
    spaces: 5,
    rating: 4,
    image: "https://images.pexels.com/photos/59197/pexels-photo-59197.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 7,
    title: "Science Experiments",
    description: "Hands-on experiments to discover how the world works.",
    location: "Science Lab",
    price: 23.0,
    spaces: 5,
    rating: 5,
    image: "https://images.pexels.com/photos/2280551/pexels-photo-2280551.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 8,
    title: "Dance Workshop",
    description: "Learn fun routines and boost your confidence on stage.",
    location: "Dance Studio",
    price: 19.0,
    spaces: 5,
    rating: 4,
    image: "https://images.pexels.com/photos/3771837/pexels-photo-3771837.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 9,
    title: "Creative Writing",
    description: "Create stories, poems and characters from your imagination.",
    location: "Room 202",
    price: 15.0,
    spaces: 5,
    rating: 4,
    image: "https://images.pexels.com/photos/261949/pexels-photo-261949.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 10,
    title: "Math Puzzles Club",
    description: "Solve fun math puzzles and brain teasers together.",
    location: "Room 105",
    price: 12.0,
    spaces: 5,
    rating: 5,
    image: "https://images.pexels.com/photos/59197/pexels-photo-59197.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
];

module.exports = { courses };